### PR TITLE
fix: implement annotation pruning for pods that no longer match filters

### PR DESCRIPTION
**Pull request by benosman**
When filters are modified, and pods or volumes that are previously managed are now excluded, currently the controller does not remove the annotations from the pod.

This pull request aims to fix that and the way it works is to introduce a 'managed' annotation that is added when a pod's volumes are added to the velero annotation.

Then, when a pod has no matching volumes, the controller checks if the 'managed' annotation is present, if it is then the velero annotation is removed from the pod. This check takes place when checking the pod's filters (e.g. namespace) and also when a matching pod has 0 included volumes.

The reason for using a managed flag is to allow velero annotations to be applied manually or by other tools without conflicts.

The name of the managed flag (and it's constant name) is open to suggestion. Currently I have gone for the following:

```go
POD_BACKUP_MANAGED_ANNOTATION_KEY     = "vvc.velero.io/backup-volumes-managed"
```

I have been working on this as part of a series of changes, but I have now rebased it on the changes by @fredgate in #8

### CODE REVIEW

**Comment by duyanghao** [comment]
IMO, there is no need to add another restic backup annotation since the existing `backup.velero.io/backup-volumes` annotation can support what you want to do here in this PR.

**Comment by benosman** [comment]
> IMO, there is no need to add another restic backup annotation since the existing `backup.velero.io/backup-volumes` annotation can support what you want to do here in this PR.

Could you explain how it can support this? Perhaps i'm missing something, but the idea of using the additional annotation is to allow other tools to coexist with this controller.

Just implementing the annotation removal on its own would mean that if you manually set an annotation on a pod that is excluded by the rules, then this controller would eventually remove that annotation.

**Comment by duyanghao** [comment]
> > IMO, there is no need to add another restic backup annotation since the existing `backup.velero.io/backup-volumes` annotation can support what you want to do here in this PR.
> 
> Could you explain how it can support this? Perhaps i'm missing something, but the idea of using the additional annotation is to allow other tools to coexist with this controller.

Firstly, What I mean here is that you can achieve the same logic and feature when replacing `vvc.velero.io/backup-volumes-managed` with `backup.velero.io/backup-volumes`. I can't figure out the necessity of adding another annotation.

```
pod:    pod1    pod2   pod3
filter:   A      B        C
Round#1: filter A, both pod2 and pod3 adds `backup.velero.io/backup-volumes`
Round#2: filter B, pod1 adds `backup.velero.io/backup-volumes`, pod2 deletes `backup.velero.io/backup-volumes`, pod3 adds `backup.velero.io/backup-volumes`  
Round#3: filter C, pod1 adds `backup.velero.io/backup-volumes`, pod2 adds `backup.velero.io/backup-volumes`, pod3 delete `backup.velero.io/backup-volumes`
```

> Just implementing the annotation removal on its own would mean that if you manually set an annotation on a pod that is excluded by the rules, then this controller would eventually remove that annotation.

I don't get your point, Is that remove.the annotation not correct logic when pod can't meet filter options?

**Comment by benosman** [comment]
> I don't get your point, Is that remove.the annotation not correct logic when pod can't meet filter options?

The logic works fine if we want to assign velero-volume-controller 100% ownership of all velero backup annotations in the cluster. 

It falls down when, perhaps due to the currently limited volume filtering options, you want to manage volumes in an excluded namespace manually. Without the additional annotation (or some other way of tracking state), this controller would just remove your annotations.

**Comment by duyanghao** [comment]
> It falls down when, perhaps due to the currently limited volume filtering options, you want to manage volumes in an excluded namespace manually. Without the additional annotation (or some other way of tracking state), this controller would just remove your annotations.

@benosman IMO, it's not a good idea to support the backup of pod which can't meet filter options by adding another annotation:
1. Backuping pods that can't meet filter options is not a common demand.
2. Adding another annotation will increases the complexity of this controller.

And there are two suggestions: 
1. Add `delete annotation` logic when pod can't meet filter options.
2. Specify more filter options to support the usage scenario that the first suggestion can't cover(i.e. `manage volumes in an excluded namespace`).

**Comment by benosman** [comment]
I have force pushed a simpler version that does not use an additional annotation. 

It just tries to remove annotations when the the pod/volumes don't match the filters.

**Comment by duyanghao** [comment]
LGTM. @benosman Thanks for your PR.

**Pull request merged**
